version: '2'

services:

  proxy:
    build: proxy
    container_name: proxy
    ports:
      - 80:80

  frontend:
    build: frontend
    container_name: frontend
    ports:
      - 8001:80

  backend:
    build: backend
    container_name: backend
    ports:
      - 8002:80
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /home/pi/db.sqlite3:/app/db.sqlite3
    privileged: true
