version: '2'

services:

  proxy:
    image: raposfly-proxy
    build: services/proxy
    ports:
      - 80:80

  frontend:
    image: raposfly-frontend
    build: services/frontend
    ports:
      - 8001:80

  backend:
    image: raposfly-backend
    build: services/backend
    environment:
      - RAPOSFLY_PRODUCTION=1
    ports:
      - 8002:80
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /run/systemd:/run/systemd
      - /var/lib/raposfly/:/var/lib/raposfly/
    privileged: true

  backup:
    image: raposfly-backup
    build: services/backup
    volumes:
      - /var/lib/raposfly/:/var/lib/raposfly/
