version: '2'

services:

  proxy:
    build: proxy
    container_name: proxy
    ports:
      - 80:80

  frontend:
    build: frontend
    container_name: frontend
    ports:
      - 8001:80

  backend:
    build: backend
    container_name: backend
    environment:
      - RAPOSFLY_PRODUCTION=1
    ports:
      - 8002:80
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /run/systemd:/run/systemd
      - /var/lib/raposfly/db.sqlite3:/var/lib/raposfly/db.sqlite3
    privileged: true

  backup:
    build: backup
    container_name: backup
    volumes:
      - /var/lib/raposfly/backups/:/var/lib/raposfly/backups/
      - /var/lib/raposfly/db.sqlite3:/var/lib/raposfly/db.sqlite3
